# Opt out of Analytics
opt_out_usage

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane(
#   nightly: true
#   )

default_platform(:ios)

platform :ios do

  lane :localsign do
    # sync_code_signing(type: "appstore") 
    sync_code_signing(
      type: "appstore",
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      keychain_name:"login.keychain",
      keychain_password:"Changeme@1",
      app_identifier: ["com.ncmd.publicreactnativeapp"],
      readonly:true
      )
  end

  lane :localmatch do
    match(
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      app_identifier: "com.ncmd.publicreactnativeapp",
      type: "appstore",
      clone_branch_directly: true,
      readonly: true,
      keychain_name: "login.keychain",
      keychain_password: "Changeme@1"
    )
  end

  lane :localgym do

    sync_code_signing(
      type: "appstore",
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      keychain_name:"login.keychain",
      keychain_password:"Changeme@1"
      )

    get_provisioning_profile

    gym(
      scheme: "publicreactnativeapp",
      clean: true,
      silent: true,
      project: "./publicreactnativeapp.xcodeproj",
      include_bitcode: false,
      codesigning_identity:"iPhone Distribution: Charles Chong (9S2JY9AX68)",
      export_options: {
        method: "app-store",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false,
        provisioningProfiles: { 
          "com.ncmd.publicreactnativeapp" => "match AppStore com.ncmd.publicreactnativeapp"
        }
      }
    )
  end

  lane :localupload do
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

  lane :local do
    # capture_screenshots(
    #   scheme: "publicreactnativeapp",
    # )
    
    # ONLY DO THIS IF NO KEYCHAIN
    # create_keychain(
    #   name: "login.keychain",
    #   password: "Changeme@1",
    #   default_keychain: true,
    #   unlock: true,
    #   timeout: 3600,
    #   add_to_search_list: true
    # )

    # Unlock local keychain to prevent password popup
    unlock_keychain(
      path: "./login.keychain",
      add_to_search_list: :replace,
      password: "Changeme@1"
    )
    # Download certificate store from github repo
    match(
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      app_identifier: "com.ncmd.publicreactnativeapp",
      type: "appstore",
      clone_branch_directly: true,
      readonly: true,
      keychain_name: "login.keychain",
      keychain_password: "Changeme@1"
    )
    # Increment build number
    increment_build_number(
     xcodeproj: "./publicreactnativeapp.xcodeproj"
    )
    # Build App
    gym(
      scheme: "publicreactnativeapp",
      clean: true,
      silent: true,
      project: "./publicreactnativeapp.xcodeproj", # since using pods
      include_bitcode: false,
      export_options: {
        method: "app-store",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false,
        provisioningProfiles: { 
          "com.ncmd.publicreactnativeapp" => "match AppStore com.ncmd.publicreactnativeapp"
        }
      }
    )
    # Upload to App Store
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

  desc "travis enable"
  lane :travisenable do |values|
    setup_travis
  end

  lane :travismatch do |values|

    # create_keychain(
    #   name: ENV["MATCH_KEYCHAIN_NAME"],
    #   password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    #   default_keychain: true,
    #   unlock: true,
    #   timeout: 3600,
    #   add_to_search_list: true
    # )
    

    unlock_keychain(
      path: "fastlane_tmp_keychain",
      add_to_search_list: :replace,
      password: "Changeme@1"
    )

    # register_devices(
    #   devices: {
    #     "Travis iPhone X" => "1234567890123456789012345678901234567890"
    #   }
    # ) # 

    # match(
    #   app_identifier: "com.ncmd.publicreactnativeapp",
    #   type: "appstore",
    #   # force_for_new_devices: !is_ci,
    #   git_url:"https://github.com/ncmd/public-fastlane-certificates",
    #   # clone_branch_directly: true,
    #   readonly: true,  #readonly mode to be sure it won't create any new certificates or profiles.
    #   keychain_name: "login.keychain",
    #   keychain_password: "Changeme@1"
    # )

    sync_code_signing(
      type: "appstore",
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      keychain_name: "fastlane_tmp_keychain",
      keychain_password: "Changeme@1"
      )

  end

  lane :travisgym do |values|

    unlock_keychain(
      path: "login.keychain",
      add_to_search_list: :replace,
      password: "Changeme@1"
    )

    match(
      app_identifier: "com.ncmd.publicreactnativeapp",
      type: "appstore",
      force_for_new_devices: !is_ci,
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      # clone_branch_directly: true,
      readonly: true,  #readonly mode to be sure it won't create any new certificates or profiles.
      keychain_name: "login.keychain",
      keychain_password: "Changeme@1"
    )
    
    import_certificate(
      keychain_name:"login.keychain",
      keychain_password:"Changeme@1",
      certificate_path: "./ios_distribution.cer"
    )

    gym(
      scheme: "publicreactnativeapp",
      codesigning_identity:"iPhone Distribution: Charles Chong (9S2JY9AX68)",
      clean: true,
      silent: true,
      project: "./publicreactnativeapp.xcodeproj",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates",
      include_bitcode: false,
      suppress_xcode_output: true,
      disable_xcpretty: true,
      export_options: {
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false,
        provisioningProfiles: { 
          "com.ncmd.publicreactnativeapp" => "match AppStore com.ncmd.publicreactnativeapp"
        }
      }
    )
  end

  lane :travisupload do |values|
    increment_build_number(
     xcodeproj: "./publicreactnativeapp.xcodeproj"
    )

    # Upload to App Store
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

  desc "travis test"
  lane :travistest do |values|

    # create_keychain(
    #   name: "login.keychain",
    #   password: "Changeme@1",
    #   default_keychain: true,
    #   unlock: true,
    #   timeout: 3600,
    #   add_to_search_list: true
    # )

    # unlock_keychain(
    #   path: "./fastlane_tmp_keychain",
    #   add_to_search_list: :replace,
    #   password: "Changeme@1"
    # )

    # unlock_keychain(
    #   path: "login.keychain",
    #   add_to_search_list: :replace,
    #   password: "Changeme@1"
    # )
    
    # match(
    #   app_identifier: "com.ncmd.publicreactnativeapp",
    #   type: "appstore",
    #   force_for_new_devices: !is_ci,
    #   git_url:"https://github.com/ncmd/public-fastlane-certificates",
    #   # clone_branch_directly: true,
    #   readonly: true,  #readonly mode to be sure it won't create any new certificates or profiles.
    #   keychain_name: "login.keychain",
    #   keychain_password: "Changeme@1"
    # )

    # increment_build_number(
    #  xcodeproj: "./publicreactnativeapp.xcodeproj"
    # )

    # xcversion(version: "9.3")

    # ensure_xcode_version(version: "9.3")

    build_ios_app(
      scheme: "publicreactnativeapp",
      silent: true,
      clean: true,
      suppress_xcode_output: true,
      disable_xcpretty: true,
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "com.ncmd.publicreactnativeapp" => "match AppStore com.ncmd.publicreactnativeapp"
        }
      }
    )

    # Upload to App Store
    # upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

  desc "travis deployment"
  lane :travis do |values|
    # Before calling match, we make sure all our devices are registered on the Apple Developer Portal
    # setup_travis

    # create_keychain(
    #   name: ENV["MATCH_KEYCHAIN_NAME"],
    #   password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    #   default_keychain: true,
    #   unlock: true,
    #   timeout: 3600,
    #   add_to_search_list: true
    # )

    create_keychain(
      name: "login.keychain",
      password: "Changeme@1",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    # Create keychain for travis https://docs.fastlane.tools/actions/setup_travis/#setup_travis
 
    # unlock_keychain(
    #   path: ENV["MATCH_KEYCHAIN_PATH"],
    #   add_to_search_list: :replace,
    #   password: ""
    # )

    # /Users/travis/Library/Keychains/fastlane_tmp_keychain-db
    unlock_keychain(
      path: "login.keychain",
      add_to_search_list: :replace,
      password: "Changeme@1"
    )
    
    match(
      app_identifier: "com.ncmd.publicreactnativeapp",
      type: "appstore",
      force_for_new_devices: !is_ci,
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      # clone_branch_directly: true,
      readonly: true,  #readonly mode to be sure it won't create any new certificates or profiles.
      keychain_name: "login.keychain",
      keychain_password: "Changeme@1"
    )

    # register_devices(
    #   username: "cchong.vise@gmail.com",
    #   platform: "ios",
    #   devices: {
    #     "travisx" => "a123456789012345678901234567890123456789",
    #     "travis6" => "b123456789012345678901234567890123456789"
    #   }
    # )
 
    # Change build number (requirement of Testflight).
    increment_build_number(
     xcodeproj: "./publicreactnativeapp.xcodeproj"
    )
 
    # Build a release
    gym(
      scheme: "publicreactnativeapp",
      clean: true,
      include_bitcode: false,
      project: "./publicreactnativeapp.xcodeproj",
      export_options: {
        method: "app-store",
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false,
        provisioningProfiles: { 
          "com.ncmd.publicreactnativeapp" => "match AppStore com.ncmd.publicreactnativeapp"
        }
      }
    )

    # Upload to App Store
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)

  end
end