# Opt out of Analytics
opt_out_usage

update_fastlane

default_platform(:ios)

platform :ios do

  lane :localsetup do
    sync_code_signing(
      type: "appstore",
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      keychain_name:"login.keychain"
      )
  end

  lane :localsnapshot do
    snapshot(
      project: 'publicreactnativeapp.xcodeproj',
      scheme: 'publicreactnativeappUITests',
      devices: ['iPhone 6s Plus'],
      languages: ["en-US"],
      output_simulator_logs: true,
      clear_previous_screenshots: true,
      output_directory: "./fastlane/screenshots",
      number_of_retries: 0,
      concurrent_simulators: false,
  )
  end

  lane :localdeliver do
    current_build_number = get_build_number(xcodeproj: "publicreactnativeapp.xcodeproj")

    deliver(
      build_number: current_build_number,
      precheck_include_in_app_purchases: false,
      overwrite_screenshots: true,
      screenshots_path: "./fastlane/screenshots",
      submit_for_review: false,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: false,
      skip_binary_upload: true,
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      },
    )
    upload_to_app_store(skip_metadata: false, skip_screenshots: false, force: true)
  end

  lane :localdeploy do
    
    sync_code_signing(
      type: "appstore",
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      keychain_name:"login.keychain"
      )
    increment_build_number
    increment_version_number(
      bump_type: "minor",
      xcodeproj: "./publicreactnativeapp.xcodeproj"
    )
    build_app(
      scheme: "publicreactnativeapp")
    
    snapshot(
      project: 'publicreactnativeapp.xcodeproj',
      scheme: 'publicreactnativeappUITests',
      devices: ['iPhone 6s Plus'],
      languages: ["en-US"],
      output_simulator_logs: true,
      clear_previous_screenshots: true,
      output_directory: "./fastlane/screenshots",
      number_of_retries: 0,
      concurrent_simulators: false,
    )
    current_build_number = get_build_number(xcodeproj: "publicreactnativeapp.xcodeproj")

    deliver(
      build_number: current_build_number,
      precheck_include_in_app_purchases: false,
      overwrite_screenshots: true,
      screenshots_path: "./fastlane/screenshots",
      submit_for_review: false,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: false,
      skip_binary_upload: false,
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      }
    )
    upload_to_app_store(skip_metadata: false, skip_screenshots: false, force: true)
  end

  lane :travisdeploy do |values|
    setup_travis
    sync_code_signing(
      type: "appstore",
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      keychain_name:"fastlane_tmp_keychain"
      )
      increment_build_number
      increment_version_number(
        bump_type: "minor"
      )
    build_app(
      scheme: "publicreactnativeapp",
      include_bitcode: false,
      export_method: "app-store",
      export_options: {
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false,
        provisioningProfiles: { 
          "com.ncmd.publicreactnativeapp" => "match AppStore com.ncmd.publicreactnativeapp"
        }
      }
    )
    snapshot(
      project: 'publicreactnativeapp.xcodeproj',
      scheme: 'publicreactnativeappUITests',
      devices: ['iPhone 6s Plus'],
      languages: ["en-US"],
      output_simulator_logs: true,
      clear_previous_screenshots: true,
      output_directory: "./fastlane/screenshots",
      number_of_retries: 0,
      concurrent_simulators: false,
    )
    current_build_number = get_build_number(xcodeproj: "publicreactnativeapp.xcodeproj")

    deliver(
      build_number: current_build_number,
      precheck_include_in_app_purchases: false,
      overwrite_screenshots: true,
      screenshots_path: "./fastlane/screenshots",
      submit_for_review: false,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: false,
      skip_binary_upload: false,
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: true,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false
      }
    )
    upload_to_app_store(skip_metadata: true, skip_screenshots: true, force: true)
  end
end