# Opt out of Analytics
opt_out_usage

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Local Build App"
  lane :localdeploy do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    capture_android_screenshots
    build_android_app(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(
      apk: './app/build/outputs/apk/release/app-release.apk'
    )
  end

  desc "Build App"
  lane :build do
    gradle(
      task: 'assemble',
      build_type: 'Release',
      properties: {
        'android.useDeprecatedNdk' => true,
        'android.injected.signing.store.file' => 'my-release-key.keystore',
        'android.injected.signing.store.password' => ENV["MYAPP_RELEASE_STORE_PASSWORD"],
        'android.injected.signing.key.alias'=> ENV["MYAPP_RELEASE_KEY_ALIAS"],
        'android.injected.signing.key.password' => ENV["MYAPP_RELEASE_KEY_PASSWORD"]
      }
    )
    # capture_android_screenshots
    upload_to_play_store(
      apk: './app/build/outputs/apk/release/app-release.apk'
    )
  end
end